
### FindAll
GET http://localhost:3000/users

### FindOne
GET http://localhost:3000/users/fuga

### CreatePost
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "hoge",
  "password": "asdfasdf",
  "description": "hogehogehoge"
}

### UpdatePost
PUT  http://localhost:3000/users
Content-Type: application/json

{
  "username": "fuga",
  "password": "asdfasdf",
  "description": "fugafugafuga"
}

### DeletePost
DELETE http://localhost:3000/users/fuga

### Auth jet Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "fuga",
  "password": "asdfasdf"
}